<?php
/**
 * Copyright 2020 Adorncommerce LLP. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \Magento\Review\Block\Product\Review $block */
$helper = $this->helper('Adorncommerce\ProductReviewRating\Helper\Data');
?>
<div id="product-review-container" data-role="product-review"></div>
<?= $block->getChildHtml() ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->getProductReviewUrl()) ?>",
                "reviewsTabSelector": "#tab-label-reviews",
                "module": "<?= $helper->isModuleEnabled() ?>"
            }
        }
    }
</script>
